export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: "var(--brand-primary)",
          "primary-hover": "var(--brand-primary-hover)",
          soft: "var(--brand-soft)",
          accent: "var(--text-secondary)",
        },
        plum: {
          900: "var(--text-primary)",
          800: "var(--brand-primary-hover)",
          700: "var(--brand-primary)",
          600: "var(--brand-primary)",
          500: "var(--text-secondary)",
          200: "var(--border)",
          100: "var(--brand-soft)",
          50: "var(--surface-subtle)",
        },
        copper: {
          700: "var(--text-primary)",
          600: "var(--text-secondary)",
          500: "var(--text-secondary)",
          100: "var(--surface-muted)",
          50: "var(--surface-subtle)",
        },
        ivory: {
          900: "var(--text-primary)",
          700: "var(--text-secondary)",
          500: "var(--text-muted)",
          200: "var(--border)",
          100: "var(--surface-muted)",
          50: "var(--page-background)",
        },
        navy: { 900: "var(--text-primary)", 700: "var(--text-secondary)" },
        blue: { 600: "var(--brand-primary)", 50: "var(--brand-soft)" },
        teal: { 600: "var(--success-text)", 50: "var(--success-background)" },
        amber: { 600: "var(--pending-text)", 50: "var(--pending-background)" },
        red: { 600: "var(--danger-text)", 50: "var(--danger-background)" },
        charcoal: { 900: "var(--text-primary)", 600: "var(--text-secondary)" },
        status: {
          success: "var(--success-text)",
          "success-bg": "var(--success-background)",
          pending: "var(--pending-text)",
          "pending-bg": "var(--pending-background)",
          danger: "var(--danger-text)",
          "danger-bg": "var(--danger-background)",
          neutral: "var(--text-secondary)",
          "neutral-bg": "var(--surface-muted)",
        },
        border: "var(--border)",
        bg: "var(--page-background)",
        surface: "var(--surface)",
        "surface-muted": "var(--surface-muted)",
      },
      borderRadius: { DEFAULT: "10px", xl: "12px" },
      spacing: { unit: "8px" },
      fontFamily: { sans: ["Inter", "system-ui", "sans-serif"] },
    },
  },
  plugins: [],
};
